# This is a basic workflow to help you get started with Actions

name: Generate and publish ontology documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  doc:
    runs-on: ubuntu-latest
    env:
      WIDOCO_DOWNLOAD_URL: https://github.com/dgarijo/Widoco/releases/download/v1.4.17/java-11-widoco-1.4.17-jar-with-dependencies.jar
    steps:
      - uses: actions/checkout@v3

      - name: Cache Widoco
        uses: actions/cache@v3
        with:
          path: jar
          key: ${{ env.WIDOCO_DOWNLOAD_URL }}

      - name: Download Widoco if it doesn't exist
        run: |
          mkdir -p jar
          if test -f jar/widoco.jar; then echo "Widoco already exists, skipping download."; exit 0; fi
          wget $WIDOCO_DOWNLOAD_URL --progress=dot:giga --output-document=jar/widoco.jar
          
      - name: Run Widoco
        run: java -jar jar/widoco.jar -ontFile rare-disease-simulation_v3.0.owl -oops -uniteSections -getOntologyMetadata -outFolder doc -rewriteAll

      - name: Rename index-en.html to index.html
        run: mv doc/index-en.html doc/index.html
      
      - name: Deploy Documentation to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: doc
          single-commit: true
